CREATE DATABASE api_noticias;
USE api_noticias;

CREATE TABLE autores (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  sobrenome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  sexo ENUM("F", "M") NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  alterado_em DATETIME DEFAULT NULL,
  deletado_em DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE noticias (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  autor_id INT NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  subtitulo VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  publicada_em DATETIME,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  alterado_em DATETIME DEFAULT NULL,
  deletado_em DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE imagens_noticias (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  noticia_id INT NOT NULL,
  imagem LONGTEXT NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  alterado_em DATETIME DEFAULT NULL,
  deletado_em DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE noticias
  ADD CONSTRAINT autor_id_fk FOREIGN KEY (autor_id) REFERENCES autores (id) ON DELETE CASCADE;

ALTER TABLE imagens_noticias
  ADD CONSTRAINT noticia_id_fk FOREIGN KEY (noticia_id) REFERENCES noticias (id) ON DELETE CASCADE;

